title:            Papo de Cloud
description:      Cloud Computing. No seu idioma.
logo: cloud-chat2.png
disqus_shortname: papodecloud
share: true
dropcap: true

# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  http://www.papodecloud.com.br
#url:             http://localhost:4000

# Owner/author information
owner:
  name:           Papo de Cloud
  # avatar:         hmfaysal.jpg
  # email:          contato@papodecloud.com.br
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  # description:    Awesome Dude, Awesome Life
  # Social networking links used in footer. Update and remove as you like.
  twitter:        papodecloud
  # facebook:       papodecloud
  # github:         papodecloud
  # instagram:      papodecloud
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    https://plus.google.com/u/0/102602916593522619858

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-40970227-2
# google_verify:
# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Posts em destaque
    url: /destaques
  - title: Categorias
    url: /categorias
  - title: Sobre
    url: /sobre

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "pagina:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year-:month-:day-:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# Gems
gems: [jekyll-paginate]
